name: uruqai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - geopandas
  - numpy
  - scikit-learn
  - shapely
  - pyproj
  - requests
  - sqlalchemy
  - jinja2
  - streamlit
  - qiskit
  - dwave-ocean-sdk
  - pytest
  - black
  - ruff
  - mypy
  - make
  - pip
  - pip:
      - gurobipy
      - dvc
